### ISSUE TITLE
Missing if __name__ == "__main__"

### ISSUE THREAD

**Issue by jferard** [geoffroychaussonnet/script_to_monitor_Covid19#12]
I noticed that running:

     python3 -m pytest --doctest-modules

has an annoying side effect: diagrams are displayed. We should have a `main` function in each script and the two lines:

    if __name__ == "__main__":
        main()

See https://stackoverflow.com/a/28336701/6914441 for more information.

**Comment by geoffroychaussonnet** [comment]
ok, I'll change it soon

**Comment by geoffroychaussonnet** [comment]
solved with commit 5257676601b236fb4f9a69a68bbb4c6256af48ea

**Comment by jferard** [comment]
Nice. Now 

    $ python3 -m pytest --doctest-modules

works fine, and I can run scripts from my IDE (PyCharm).
