### ISSUE TITLE
dependence on pathlib

### ISSUE THREAD

**Issue by geoffroychaussonnet** [geoffroychaussonnet/script_to_monitor_Covid19#6]
It seems that pathlib is not installed by default with a "typical python" installation:
`ImportError: No module named pathlib`

If it is not a sub-library of matplotlib, numpy or pandas, it should be mentioned in the requirements

**Comment by jferard** [comment]
It's strange: [pathlib module](https://docs.python.org/3/library/pathlib.html) exists since python 3.4:

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> 
```

**Comment by geoffroychaussonnet** [comment]
My bad : i had this problem with Python 2.7, which is not supposed to be used with the scripts.
